language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t test/react_app_test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true test/react_app_test npm test

after_success:
  - docker build -t test/react_app_client ./client
  - docker build -t test/react_app_nginx ./nginx
  - docker build -t test/react_app_server ./server
  - docker build -t test/react_app_worker ./worker